# I've come across a problem when trying to use Travis CI to automate my blog deployment. The Travis CI site says "We are unable to start your build at this time. You exceeded the number of users allowed for your plan. Please review your plan details and follow the steps to resolution."
sudo: false
language: node_js
node_js:
  - 22
cache: npm
branches:
  only:
    - main # build main branch only
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main # build main branch only
  local-dir: public
