# hexo-pwa
pwa:
  manifest:
    path: /manifest.json
    body:
      name: CINÉPHILE
      short_name: Cine's Blog
      icons:
        - src: /images/favicon-16.png
          sizes: 16x16
          type: image/png
        - src: /images/favicon-48.png
          sizes: 48x48
          type: image/png
        - src: /images/favicon-96.png
          sizes: 96x96
          type: image/png
        - src: /images/favicon-128.png
          sizes: 128x128
          type: image/png
        - src: /images/favicon-144.png
          sizes: 144x144
          type: image/png
        - src: /images/favicon-180.png
          sizes: 180x180
          type: image/png
        - src: /images/favicon-192.png
          sizes: 192x192
          type: image/png
        - src: /images/favicon-512.png
          sizes: 512x512
          type: image/png
      start_url: /
      theme_color: "#ffffff"
      background_color: "#ffffff"
      display: standalone
  serviceWorker:
    path: /sw.js
    preload:
      urls:
        - /
      posts: 6
    opts:
      networkTimeoutSeconds: 6
    routes:
      - pattern: !!js/regexp /hm.baidu.com/
        strategy: networkOnly
      - pattern: !!js/regexp /www.google-analytics.com/
        strategy: networkOnly
      - pattern: !!js/regexp /.*\.(js|css|jpg|jpeg|png|gif|webp)$/
        strategy: cacheFirst
      - pattern: !!js/regexp /\//
        strategy: networkFirst
  priority: 6
